### ISSUE TITLE
No XY Tensioner Insert with 5mm Center Pin

### ISSUE THREAD

**Issue by digitalentropy** [Caribou3d/CaribouCartesian#11]
I was surprised to find no E3D GT2 toothed idler support in any of the idler files available.

https://e3d-online.com/products/gates-powergrip%C2%AE-2gt-idlers

Any plans for support?

**Comment by wschadow** [comment]
Reliable toothed pulleys come only at least with 20T. We do not plan to changed the design of the plastic parts for that.

**Comment by digitalentropy** [comment]
> 
> 
> Reliable toothed pulleys come only at least with 20T. We do not plan to changed the design of the plastic parts for that.

Can you explain more about what changes would be needed?

The belt path on a smooth 16T vs. 20T toothed is almost identical.
