### ISSUE TITLE
10mm belt in Y axis

### ISSUE THREAD

**Issue by HjortCreations** [Caribou3d/CaribouCartesian#12]
Hello
I like the design, it feels sturdy and good.
I would like to use a 10mm wide belt on the Y axis thou, would it be possible for you to edit it or share the files for me only in .F3D??
I should be able to cut off 2mm of the belt holder on the carridge, but widening the tensioner by 4mm upwards is soo much easier when you have the original design...
I hope that you can find you time to do it...

**Comment by wschadow** [comment]
We had experimented with 9mm belts already. But did not notice any improvement. The STEP file for the full design is provided already.
