### ISSUE TITLE
Print parts

### ISSUE THREAD

**Issue by TigerClaw33** [Caribou3d/CaribouCartesian#4]
Hi, 
I printed all parts. Some of them with support. But it was not a good idea because I cannot remove the support material from all hexagonal nut slots which are inside a part. Which parts would you recommend to print with support? The Ensy Cover for example was difficult to print with support and a had a little bit warping on the bottom :(

My second question is if you would recommend to extend with titan extruder. Would it fit with MK3-templates because the zaribo files are modified ... maybe it would be a good idea for an update of the STL files for Titan Extruder ;) Or Bondtech ...

I also ordered directly from LDO and Motech some 0.9° and 1.8° steppers for bad times .... 0.9° will not make any change for a standard diameter ...

**Comment by murathanaraz** [comment]
Hi,

You can use brim on the einsy box cover, the pars with fillets are going to be fine without support. Maybe you should check your slicer settings for the supports. It sounds like yoıur support settings should be tweaked.

Cheers,

**Comment by TigerClaw33** [comment]
![pic](https://user-images.githubusercontent.com/19761951/52276176-c8d4f480-2951-11e9-8ca1-1904e5f95dbf.jpg)

I can remove the support from nut holes but in this case inside the nut hole there is another hole so I have a support as "L"-form ...

**Comment by wschadow** [comment]
Most parts of Rel can be printed without support. Add support only from bed for Einys box cover.
