### ISSUE TITLE
Calibration Problem with Zaribo V1 and V2 parts

### ISSUE THREAD

**Issue by TigerClaw33** [Caribou3d/CaribouCartesian#6]
Good morning, 

I have with three printers which are using different versions of Zaribo STL-files a problem. 

1. If I start z-calibration the nozzle crashes with the heated bed at the 3. or also 4 position for example. The PINDA has at this point no signal. So if I move the extruder a few millimeters to the right or left it gets the signal. I assembled everything very carefully and meassuret the distances and lenght of every part. 

If I change the PINDA height it will not crash but it will say "a problem occures during calibration" so it will not start the calibration. For this I found out that if I change the z-height from "320" to "318" in the firmware it works. 

I think it's because the PINDA is not able to find the right position on the heated bed with the magnets. I have no other explanation.

Did you have similar issues with some printers? I can also work without calibration because if I put a steel sheet on the bed it works fine.

**Comment by wschadow** [comment]
Sounds more like a PINDA or FW issue. Since it refers to an old version I will close this issue.
