### ISSUE TITLE
OLED-105 found twice in STL folder

### ISSUE THREAD

**Issue by rderimay** [Caribou3d/CaribouCartesian#8]
Hi there,

there are two slightly different versions of the OLED cover in the repo, as well as a .gcode file:
`OLED-105 cover.stl`
`OLED-105-Cover.stl`
`OLED-105 Cover.gcode`

IMO, `OLED-105-Cover.stl` and `OLED-105 Cover.gcode` should be deleted and `OLED-105 cover.stl`, which is the design with more clearance, should be renamed to `OLED-105-Cover.stl`.

**Comment by wschadow** [comment]
Thanks for pointing out the issue. Files have been replaced and moved to OLED folder.
