### ISSUE TITLE
Mosquito STL

### ISSUE THREAD

**Issue by TigerClaw33** [Caribou3d/CaribouCartesian#9]
Hi, 

do the carriage (8 and 10mm) fits with this mosquito upgrade: https://www.thingiverse.com/thing:3515782

And do you have plans to design your own Zaribo STL for Mosquito hotends independen from bondtech extruder?

**Comment by wschadow** [comment]
Hi,
we haven't tried the part. As long as it has the same form factor as the original Bondtech housing it will work.

We have no plane to design our own housing for this.
